name: Build and Release

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-binary:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout SCM
        uses: actions/checkout@v1

      - name: Get dependancies
        run: GO111MODULE=on go mod download

      - name: Vendoring
        run: go mod vendor

      - name: Build binary
        run: go build -o redis_migrator ./app

      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}-redis_migrator
          path: redis_migrator

  make_release:
    needs: build-binary
      name: Release
      runs-on: ubuntu-latest

    - name: Make release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Save upload assets URL
      run: echo ${{ steps.create_release.outputs.upload_url }} > upload_url.txt

    - name: Upload assets URL
      uses: actions/upload-artifact@v1
      with:
        name: upload_url.txt
        path: upload_url.txt

  release:
    needs: build-binary
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    name: Release
    steps:
      - name: Download binary
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.platform }}-redis_migrator
          path: ${{ matrix.platform }}-redis_migrator

      - name: Download upload URL asset
        uses: actions/download-artifact@v1
        with:
          name: upload_url.txt
          path: upload_url.txt

      - name: Set upload URL as env
        run: echo "::set-env name=UPLOAD_URL::$(cat upload_url.txt)"

      - name: Set content type
        run: echo "::set-env name=CONTENT_TYPE::$(file --mime-type -b redis_migrator)"

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ UPLOAD_URL }}
          asset_path: ${{ matrix.platform }}-redis_migrator
          asset_name: ${{ matrix.platform }}-redis_migrator
          asset_content_type: ${{ CONTENT_TYPE }}
